<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="TmpSuite" duration-ms="15" started-at="2018-09-04T10:10:41Z" finished-at="2018-09-04T10:10:41Z">
    <groups>
    </groups>
    <test name="TmpTest" duration-ms="15" started-at="2018-09-04T10:10:41Z" finished-at="2018-09-04T10:10:41Z">
      <class name="com.yoozoo.testng.demo.MyClass">
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="test2" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.yoozoo.testng.demo.MyClass.test2(MyClass.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.yoozoo.testng.demo.MyTestNG.main(MyTestNG.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="beforeTest" is-config="true" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="test4()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="test4" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [111]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [111]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:509)
	at org.testng.Assert.assertNull(Assert.java:445)
	at org.testng.Assert.assertNull(Assert.java:434)
	at com.yoozoo.testng.demo.MyClass.test4(MyClass.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.yoozoo.testng.demo.MyTestNG.main(MyTestNG.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="beforeTest" is-config="true" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="test1()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="test1" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test3()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="test3" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="beforeTest" is-config="true" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="beforeTest" is-config="true" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.yoozoo.testng.demo.MyClass@e73f9ac]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-09-04T18:10:41Z" finished-at="2018-09-04T18:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.yoozoo.testng.demo.MyClass -->
    </test> <!-- TmpTest -->
  </suite> <!-- TmpSuite -->
</testng-results>
