<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="upc3086" ignored="0" name="TmpTest" tests="4" failures="2" timestamp="04 九月 2018 10:10:41 GMT" time="0.015" errors="0">
  <testcase name="test1" time="0.0" classname="com.yoozoo.testng.demo.MyClass"/>
  <testcase name="test2" time="0.0" classname="com.yoozoo.testng.demo.MyClass">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.yoozoo.testng.demo.MyClass.test2(MyClass.java:24)
	at com.yoozoo.testng.demo.MyTestNG.main(MyTestNG.java:35)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.yoozoo.testng.demo.MyClass"/>
  <testcase name="test4" time="0.0" classname="com.yoozoo.testng.demo.MyClass">
    <failure type="java.lang.AssertionError" message="expected [null] but found [111]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [111]
	at com.yoozoo.testng.demo.MyClass.test4(MyClass.java:32)
	at com.yoozoo.testng.demo.MyTestNG.main(MyTestNG.java:35)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- TmpTest -->
